FROM ubuntu:latest
RUN apt-get update && apt-get install nginx
COPY nginx.conf /etc/nginx/conf.d
VOLUME myvolume1
WORKDIR /opt
EXPOSE 8080
CMD ['nginx' '-D' 'forground']

#to build docker image
$docker build -t nginx:1.10 .

#to create docker container
$docker run -d -p 8080:8080 --name ingnginx nginx:1.10
